fix: add duckdb as dependency
ibis-project/ibisml pull request #152
Opened 2024-09-05 19:16 UTC by jitingxu1

For Ibis default installation, it removed numpy and pandas as required dependencies: https://github.com/ibis-project/ibis/pull/9564

I did not have experience with package dependency managment,  I have two options

1. add pandas and numpy as required dependency in IbisML
2. add a backend (duckdb) for ibis installation, anyhow, we need to install one backend (duckdb) to run IbisML

I have no idea which one is better, or there is other better ones, 

I took option 2, please take a look @lostmygithubaccount @deepyaman 

If it is not urgent, we could wait for Deepyaman back.

solve #151

2024-09-09 20:55 UTC, deepyaman commented
We should not force the user to install the DuckDB backend, when IbisML can work without it. Option 1 is the correct answer.

2024-09-12 18:13 UTC, jitingxu1 commented
local import numpy pandas pyarrow

2024-09-12 18:39 UTC, deepyaman requested changes
Minor change request. Can you also add a test case to make sure things work without the pandas/numpy dependency?

2024-09-12 18:39 UTC, deepyaman commented on ibis_ml/core.py
> +@normalize_table.register("pa.Table")
The changes for PyArrow are not necessary, as it is a required dependency. Can you undo them?

2024-09-12 18:40 UTC, lostmygithubaccount commented
should we be raising something if the relevant libraries aren't installed? or is the import error a user would get fine? idk what the standard practice would be

2024-09-12 18:55 UTC, jitingxu1 commented on ibis_ml/core.py
> +@normalize_table.register("pa.Table")
I did not find it is required dependency in Ibis and IbisML

https://github.com/ibis-project/ibis/blob/main/pyproject.toml#L49 was marked as optional.

2024-09-12 19:48 UTC, deepyaman commented on ibis_ml/core.py
> +@normalize_table.register("pa.Table")
OK, makes sense; I forgot about https://github.com/ibis-project/ibis/pull/9552.

Guess this is fine then, to avoid having to maintain PyArrow bounds.

2024-09-12 19:51 UTC, deepyaman commented
> should we be raising something if the relevant libraries aren't installed? or is the import error a user would get fine? idk what the standard practice would be

Import error is fine IMO for now. I'm not sure how far we're getting realistically without a backend.

2024-09-12 20:02 UTC, jitingxu1 commented
> should we be raising something if the relevant libraries aren't installed? or is the import error a user would get fine? idk what the standard practice would be

Added  tests:
- one test to make the optional dependency non-blocking.  User need to install them when they need it, it will throw an ModuleNotFoundError
- one test to import IbisML

2024-09-13 01:49 UTC, cpcloud commented on ibis_ml/core.py
> +@normalize_table.register("pa.Table")
It is a bad idea to not explicitly include dependencies that you are explicitly importing. You shouldn't really ever depend on another project to have specific dependencies.

2024-09-13 02:48 UTC, deepyaman requested changes

2024-09-13 03:33 UTC, jitingxu1 commented on tests/test_init.py
I did not try puting it in the test_core, the reason I put it in the new file becuase 1) some other files, such as _discretize.py also dependes on numpy 2) It is testing how the dependency impact the IbisML loading. I named it `test_dependenct.py` before, I am not sure if it is a good name.

2024-09-13 03:37 UTC, jitingxu1 commented on tests/test_init.py
> +        assert "ibis_ml" in sys.modules
same thing. There is a link to another [thread](https://stackoverflow.com/questions/63865618/how-to-remove-a-library-with-monkeypatch-or-mock-in-pytest/65163627#65163627)

I could change it to simpler version, no big change.

2024-09-13 03:38 UTC, jitingxu1 commented on tests/test_init.py
> +    assert "ibis_ml" in sys.modules
ah, just want to see if we could import IbisML, to see if it is working, I completely have no idea if this is the right way. Please let me know if we want to remove it.

2024-09-13 03:44 UTC, jitingxu1 commented on ibis_ml/core.py
> +@normalize_table.register("pa.Table")
> It is a bad idea to not explicitly include dependencies that you are explicitly importing. You shouldn't really ever depend on another project to have specific dependencies.

Do you mean we should explicitly include the dependency in IbisML. It is convenient users successfully imported IbisML,  but when they use it, they'll get ModuleNotFound error, have to install it.  

@deepyaman do you have any comment?

2024-09-13 16:38 UTC, deepyaman commented on tests/test_init.py
> +    assert "ibis_ml" in sys.modules
Can remove it; this doesn't do anything, since of course we need to be able to import IbisML (how else would the rest of the tests work?).

2024-09-13 16:40 UTC, deepyaman commented on tests/test_init.py
> +        assert "ibis_ml" in sys.modules
Can simplify it, if you're not sure how all this additional code is getting hit. For example, when I tested this, I was never able to hit path like `if "ibis_ml" in sys.modules`.

2024-09-13 16:53 UTC, deepyaman commented on ibis_ml/core.py
> +@normalize_table.register("pa.Table")
We don't explicitly require pandas/NumPy; we don't need to include those dependencies, unless a user is using a backend/ML framework that requires it. Those are specified in extras.

For PyArrow... trying to think, can you reasonably use IbisML without PyArrow? I took some looks at the linked PR in Ibis, and it seems there was some use case from people using Ibis internally in their product that could not need the PyArrow dependency. Is that also possible with IbisML? I wasn't completely sure...

In this case, I'm personally OK with leaving it as is, since IbisML isn't just getting a transitive dependency from Ibis—it completely relies on Ibis under the hood.

2024-09-13 20:36 UTC, jitingxu1 commented on tests/test_init.py
> +    assert "ibis_ml" in sys.modules
Great, I could remove it.

2024-09-13 20:38 UTC, jitingxu1 commented on ibis_ml/core.py
> +@normalize_table.register("pa.Table")
To unblock the release, let's keep it as it is now. We could change this later if we have new findings.

2024-09-13 21:59 UTC, deepyaman approved these changes

2024-09-13 22:09 UTC, merged