docs(website): document custom transformer step implementation
ibis-project/ibisml pull request #155
Opened 2024-09-10 17:25 UTC by ahaan1984

Re-implementation of #116, in reference to issue #47

2024-09-12 18:31 UTC, deepyaman commented
> Re-implementation of #116, closes issue #47

@ahaan1984 Thanks! I have gone ahead and approved the CI workflow (sorry I missed doing this earlier).

I'll review this soon. To help me out, can you update the description to include the high-level changes you made from #116?

2024-09-12 18:34 UTC, deepyaman requested changes, later dismissed
Just a quick comment—can you make sure to use "IbisML" (instead of "ibisML") everyhere?

2024-09-12 18:34 UTC, deepyaman commented on docs/tutorial/how_to_create_your_own_transformer.qmd
> +  This tutorial provides step-by-step guidance for creating your own ibisML transformer in Python.
```suggestion
  This tutorial provides step-by-step guidance for creating your own IbisML transformer in Python.
```

2024-09-12 18:48 UTC, ahaan1984 commented
> Just a quick comment—can you make sure to use "IbisML" (instead of "ibisML") everyhere?

Sure, will do so!

2024-09-12 19:02 UTC, ahaan1984 commented
> > Just a quick comment—can you make sure to use "IbisML" (instead of "ibisML") everyhere?
> 
> Sure, will do so!

2024-09-12 19:05 UTC, ahaan1984 commented
Have made the suggested changes, do check.

2024-09-25 21:19 UTC, deepyaman commented
> Hi. Are there any changes to be made from my end?

Sorry for the delay in getting back to you! I think this is great overall; I will go ahead and merge.

I was working on some general improvements to the content, but it looks like that work was lost when my machine was wiped without any notification; I'll see if I can revisit that at some point in the future.

Regardless, congrats on your first IbisML contribution @ahaan1984!

2024-09-25 21:21 UTC, deepyaman approved these changes
![](https://i.shipit.today/titanic)

2024-09-25 21:21 UTC, merged

2024-09-26 13:23 UTC, ahaan1984 commented
Thank you! I look forward to contributing more actively to IbisML in the future!