feat: add metrics module with classification metrics
ibis-project/ibisml pull request #176
Opened 2024-12-08 03:22 UTC by IndexSeek

I wanted to start making some progress on supporting a new `ibis_ml.metrics`
module might look like with the first pass to support classification metrics. 

In this initial pass, the functions accept the `y_pred` and `y_true` as Ibis table
expression columns.

## A few thoughts
- Should we go ahead and try this with regression metrics? Or would it be okay
to start with classification only as an "experimental" type of op.
- Do we need a "metrics" folder that contains "regression" and "classification" files?
- Is there a more effective way to test this than to compare it to scikit-learns metrics?

## What could go wrong?

I anticipate the inputs are coming from the same table expression, although testing
this behavior (or at least documenting) with what happens with input from two different
table expressions would be necessary. 

Resolves (partially) #174

2024-12-15 17:42 UTC, deepyaman commented
Sorry, I didn't see this earlier; will try to take a look soon!

2024-12-19 01:15 UTC, deepyaman requested changes
One functional request to not force compute; rest are quick nits!

2024-12-19 01:15 UTC, deepyaman commented on ibis_ml/metrics.py
> +    >>> import ibis
Nit: Can you put the `import ibis` above `from ibis_ml`? Mental `isort`ing. :P

2024-12-19 01:15 UTC, deepyaman commented on ibis_ml/metrics.py
> +    Parameters
```suggestion

    Parameters
```

2024-12-19 01:15 UTC, deepyaman commented on ibis_ml/metrics.py
> +    Parameters
```suggestion

    Parameters
```

2024-12-19 01:15 UTC, deepyaman commented on tests/test_metrics.py
> +def test_accuracy_score(results_table):
Nit: I think it would be clean to just have one parametrized test that takes a `metric` parameters. Then you can just `import ibis_ml.metrics` and `import sklearn.metrics` and `getattr(ibis_ml.metrics, metric)`, etc.

2024-12-19 03:46 UTC, IndexSeek commented on tests/test_metrics.py
> +def test_accuracy_score(results_table):
I implemented this in https://github.com/ibis-project/ibis-ml/pull/176/commits/959b45d0f78b8bedf5888ddb6f6cb10f50633bb0, this was an excellent idea and did tidy up things nicely. The previous way I was prefixing "sk_" did not feel great.

2024-12-19 03:49 UTC, IndexSeek commented on ibis_ml/metrics.py
> +    >>> import ibis
Good catch! This is fixed now in the four functions.

2024-12-19 03:53 UTC, IndexSeek commented on ibis_ml/metrics.py
> +    return (y_true == y_pred).mean().to_pyarrow().as_py()
I agree with this, it does seem strange to mix and match eager and lazy evaluation. Keeping it lazy here seems more aligned with everything else. 

I would anticipate users possibly needing to do something with thes values, like logging the metrics as part of a model's metadata. But it isn't too difficult to evaluate the expression.

2024-12-19 03:58 UTC, IndexSeek commented
Thanks for your review and the suggestions. I think these were great and have added them all now. 

I'm not sure what's going on with the build-docs check here, it seems the last time it succeeded it was using scikit-learn==1.5.2 and now it's using scikit-learn==1.6.0.

2024-12-19 09:32 UTC, deepyaman commented
> I'm not sure what's going on with the build-docs check here, it seems the last time it succeeded it was using scikit-learn==1.5.2 and now it's using scikit-learn==1.6.0.

Seems `__sklearn_tags__` is new from https://github.com/scikit-learn/scikit-learn/pull/29677; I'll have to look into it. Feel free to pin `scikit-learn <1.6.0` for now in https://github.com/ibis-project/ibis-ml/blob/main/pyproject.toml#L23.

2024-12-20 02:51 UTC, IndexSeek commented
It's pinned now at <1.6.0 for the "doc" dependencies and the check is passing! ✅

2024-12-25 15:19 UTC, deepyaman approved these changes
LGTM!

2024-12-25 15:19 UTC, merged